# fly.toml app configuration file generated for ebooksparalavida on 2026-10-02T00:51:54Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ebooksparalavida'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/'
    protocol = 'http'

[[vm]]
  memory = '2048mb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 2048
